### ISSUE TITLE
Is this a troll? Destroy Blooket.js just says "Sike Idiot"

### ISSUE THREAD

**Issue by BlooketHackerx** [CheeseDoge/blooket-hacks#1]
Are you actually working on a script that gives you all the Blooks or is this a prank. 
I want to know because if it is real and you are making a script that gives you all the blooks then this could be really cool. 
I think it is a prank because one of the files says "Sike Idiot" which means this is probably fake. 
I hope it is real and if it is then keep going!

**Comment by CheeseDoge** [comment]
Destroy Blooket.js is a troll. All blookets is not im actually working on a script. I would make a script to destroy blooket.
